remote_theme: pmarsceill/just-the-docs
title: Vantibyte Docs
url: "https://docs.vantibyte.com"
description: Documentation on how to use Vantibyte solutions
permalink: pretty
exclude: ['./README.md']

# Just-The-Docs config
footer_content: "Copyright &copy; Vantibyte"
color_scheme: dark

aux_links:
  "Main Website":
    - "//vantibyte.com"
  "Contact Us":
    - "//vantibyte.com/contact/"

ga_tracking: UA-176823557-2

# Set the vantibyte square logo as the standard for
# Twitter Cards and OpenGraph links
defaults:
  - scope:
      path: ""
    values:
      image: /assets/vblogo.png
  - scope:
      path: "en"
    values:
      lang_code: en
  - scope:
      path: "fr"
    values:
      lang_code: fr
  - scope:
      path: "es"
    values:
      lang_code: es
