remote_theme: pmarsceill/just-the-docs
title: Vantibyte Docs
description: Documentation on how to use Vantibyte solutions
permalink: pretty
exclude: ['./README.md']

# Just-The-Docs config
footer_content: "Copyright &copy; 2019-2020 Vantibyte"
color_scheme: dark

aux_links:
  "Main Website":
    - "//vantibyte.com"

# Set the vantibyte square logo as the standard for
# Twitter Cards and OpenGraph links
defaults:
  - scope:
      path: ""
    values:
      image: /assets/vblogo.png